### ISSUE TITLE
not quite sure what the issue is but i'll leave the error code here (running ubuntu 20.04 under windows WSL service)

### ISSUE THREAD

**Issue by suspect-407** [mart1nro/joycontrol#115]
Traceback (most recent call last):
  File "run_controller_cli.py", line 328, in <module>
    loop.run_until_complete(
  File "/usr/lib/python3.8/asyncio/base_events.py", line 616, in run_until_complete
    return future.result()
  File "run_controller_cli.py", line 284, in _main
    transport, protocol = await create_hid_server(factory, reconnect_bt_addr=args.reconnect_bt_addr,
  File "/home/vince/joycontrol/joycontrol/server.py", line 45, in create_hid_server
    ctl_sock = socket.socket(socket.AF_BLUETOOTH, socket.SOCK_SEQPACKET, socket.BTPROTO_L2CAP)
  File "/usr/lib/python3.8/socket.py", line 231, in __init__
    _socket.socket.__init__(self, family, type, proto, fileno)
OSError: [Errno 97] Address family not supported by protocol

**Comment by RENOxDECEPTION** [comment]
I have this error as well.

WSL2 doesn't look like it supports hardware devices:

https://www.reddit.com/r/bashonubuntuonwindows/comments/efzj4w/does_wsl_2_support_bluetooth/

**Comment by KokoseiJ** [comment]
It is generally a bad idea to use a low-level hardware dependent program on WSL2. It's just a thin wrapper over Windows, and most of the APIs directly speaking to hardwares are not implemented.
If running Linux on a bare metal is not an option, try VirtualBox. VMWare uses its own Bluetooth wrapping layer rather than passing the device directly through so you might wanna avoid it.

**Comment by kinhoy** [comment]
It seem to like that we can use https://github.com/dorssel/usbipd-win this project to make bluetooth working on WSL2, but I don't know how to use it.

**Comment by Hallstead** [comment]
Not sure if any of this is helpful, but this is my road block. After using the instructions I found to install usbipd-win as per the link in the previous comment. I have successfully attached my usb bluetooth dongle to my WSL running Ubuntu 20.04, I have taken appropriate steps to enable systemctl., and now I get a couple errors:

"org.freedesktop.DBus.Error.NameHasNoOwner: Could not get owner of name 'org.bluez': no such name"

During handling of the above exception, another exception occurred:

"org.freedesktop.DBus.Error.TimedOut: Failed to activate service 'org.bluez': timed out (service_start_timeout=25000ms)"

**Comment by virgil724** [comment]
[usbipd-win #310](https://github.com/dorssel/usbipd-win/discussions/310?sort=top#discussioncomment-2375886)

I got bluetooth work in WSL2 work well with nxbt 
with this repo i cannot got pairing succeed 
pair succeed with https://github.com/Poohl/joycontrol

**Comment by AlbertoMonteiro** [comment]
> [usbipd-win #310](https://github.com/dorssel/usbipd-win/discussions/310?sort=top#discussioncomment-2375886)
> 
> I got bluetooth work in WSL2 work well with nxbt with this repo i cannot got pairing succeed pair succeed with https://github.com/Poohl/joycontrol

I've tried it today with my Switch Lite and worked fine with nxbt

Thank you very much for that!!
