### ISSUE TITLE
AttributeError: /lib/x86_64-linux-gnu/libhidapi-hidraw.so.0: undefined symbol: hid_get_input_report

### ISSUE THREAD

**Issue by ghost** [mart1nro/joycontrol#124]
```
Traceback (most recent call last):
  File "3ds-ns.py", line 12, in <module>
    from joycontrol.protocol import controller_protocol_factory
  File "/usr/local/lib/python3.8/dist-packages/joycontrol/protocol.py", line 8, in <module>
    from joycontrol import utils
  File "/usr/local/lib/python3.8/dist-packages/joycontrol/utils.py", line 5, in <module>
    import hid
  File "/usr/local/lib/python3.8/dist-packages/hid/__init__.py", line 83, in <module>
    hidapi.hid_get_input_report.argtypes = [ctypes.c_void_p, ctypes.c_char_p, ctypes.c_size_t]
  File "/usr/lib/python3.8/ctypes/__init__.py", line 386, in __getattr__
    func = self.__getitem__(name)
  File "/usr/lib/python3.8/ctypes/__init__.py", line 391, in __getitem__
    func = self._FuncPtr((name_or_ordinal, self))
AttributeError: /lib/x86_64-linux-gnu/libhidapi-hidraw.so.0: undefined symbol: hid_get_input_report
```

**Comment by cesar0** [comment]
Have you solved this problem? Why do you encounter the same problem

**Comment by darrenchang** [comment]
Hi, I have answered this same problem at https://github.com/Poohl/joycontrol/issues/17.
I'm using this forked repository at https://github.com/Poohl/joycontrol. I think this one might have gotten outdate...
My swith version is 14.1.2. The original version. It connects fine, but the `-r` reconnect option doesn't seem to work.
