### ISSUE TITLE
Errors in detecting bluetooth device on Raspberry Pi 2 Model B

### ISSUE THREAD

**Issue by turtleisaac** [mart1nro/joycontrol#68]
Hi, I've been trying to get this running on a Raspberry Pi 2 Model B for a day or so, and after going through a bunch of other errors that were popping up, this is where I've gotten to now. It seems to me like the Pi can't see its Bluetooth chip/ adapter, and I even tried plugging a USB Bluetooth Adapter in, but nothing seems to change the result of running this command.

`$ sudo python3 run_controller_cli.py PRO_CONTROLLER
`

This is the result I get every time.

```
Traceback (most recent call last):
  File "run_controller_cli.py", line 278, in <module>
    _main(args)
  File "/usr/lib/python3.7/asyncio/base_events.py", line 584, in run_until_complete
    return future.result()
  File "run_controller_cli.py", line 189, in _main
    device_id=args.device_id)
  File "/home/pi/Desktop/joycontrol/joycontrol/server.py", line 53, in create_hid_server
    hid = HidDevice(device_id=device_id)
  File "/home/pi/Desktop/joycontrol/joycontrol/device.py", line 33, in __init__
    raise ValueError(f'Adapter {device_id} not found.')
ValueError: Adapter None not found.

```

Any ideas/ suggestions? Thanks.

**Comment by choss** [comment]
The pi 2 doesn't have bluetooth....
