### ISSUE TITLE
Random: [Errno 111] Connection refused

### ISSUE THREAD

**Issue by ebisbe** [mart1nro/joycontrol#76]
While being connected I got random disconnect errors.

Is there any limitation of triggered events or something that makes refuse the connection??

```
2020-08-04 11:30:38,056 - INFO - 192.168.0.104:52716 - "PATCH /controller/button/tap/a HTTP/1.1" 200
ERROR:asyncio:Exception in callback <function create_error_check_callback.<locals>.callback at 0xb4e61d68>
handle: <Handle create_error_check_callback.<locals>.callback>
Traceback (most recent call last):
  File "uvloop/cbhandles.pyx", line 70, in uvloop.loop.Handle._run
  File "/usr/local/lib/python3.7/dist-packages/joycontrol/utils.py", line 58, in callback
    future.result()
  File "/usr/local/lib/python3.7/dist-packages/joycontrol/protocol.py", line 155, in input_report_mode_full
    data = await reader
  File "/usr/local/lib/python3.7/dist-packages/joycontrol/transport.py", line 99, in read
    data = await self._loop.sock_recv(self._itr_sock, self._read_buffer_size)
  File "uvloop/loop.pyx", line 2430, in sock_recv
  File "uvloop/loop.pyx", line 926, in uvloop.loop.Loop._sock_recv
ConnectionRefusedError: [Errno 111] Connection refused
2020-08-04 11:30:40,068 - INFO - 192.168.0.104:52716 - "PATCH /controller/button/tap/a HTTP/1.1" 200
```

**Comment by pvanderlinden** [comment]
this is usually when the bluetooth controller power is set to off

**Comment by ebisbe** [comment]
> this is usually when the bluetooth controller power is set to off

What do you mean? I'm using a Raspberry pi. It connects and I can send commands to use the switch.

**Comment by pvanderlinden** [comment]
Mmh then I have misinterpreted what you said. But I got those kind of messages when the Bluetooth adapter power was off (which I could switch on with bluetoothctl)

**Comment by ebisbe** [comment]
> Mmh then I have misinterpreted what you said. But I got those kind of messages when the Bluetooth adapter power was off (which I could switch on with bluetoothctl)

@pvanderlinden maybe I did something wrong. What command did you execute to turn it on?

**Comment by pvanderlinden** [comment]
From the command line I ran `bluetoothctl power on` (so before starting joycontrol)
